server:
  port: 8081
  servlet:
    context-path: /oauth
  tomcat:
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
    use-relative-redirects: true

spring:
  application:
    name: oauth
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths:
            - /js/**
            - /css/**
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: oauth
